# Cross build of the Linux x86-64 game from Windows with LLVM clang and lld (docs/linux.md).
# PT_LINUX_SYSROOT: a Debian trixie amd64 sysroot (headers and libraries), made by tools/linux/make_sysroot.py.
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
if(NOT PT_LINUX_SYSROOT)
  set(PT_LINUX_SYSROOT "$ENV{PT_LINUX_SYSROOT}")
endif()
if(NOT PT_LINUX_SYSROOT)
  message(FATAL_ERROR "set PT_LINUX_SYSROOT to the Debian sysroot (tools/linux/make_sysroot.py)")
endif()
set(CMAKE_SYSROOT "${PT_LINUX_SYSROOT}")
set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES PT_LINUX_SYSROOT)
set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_C_COMPILER_TARGET x86_64-linux-gnu)
set(CMAKE_CXX_COMPILER_TARGET x86_64-linux-gnu)
set(CMAKE_ASM_COMPILER_TARGET x86_64-linux-gnu)
set(CMAKE_EXE_LINKER_FLAGS_INIT "-fuse-ld=lld")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-fuse-ld=lld")
set(CMAKE_FIND_ROOT_PATH "${PT_LINUX_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(ENV{PKG_CONFIG_SYSROOT_DIR} "${PT_LINUX_SYSROOT}")
set(ENV{PKG_CONFIG_LIBDIR} "${PT_LINUX_SYSROOT}/usr/lib/x86_64-linux-gnu/pkgconfig:${PT_LINUX_SYSROOT}/usr/share/pkgconfig")
set(CMAKE_CXX_SCAN_FOR_MODULES OFF)
